version: '3'

services:
  ortho4xp:
    build: 
      context: .
    container_name: orth4xp
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Needed for GUI
      - ./Orthophotos:/ortho4xp/Orthophotos
      - ./yOrtho4XP_Overlays:/ortho4xp/yOrtho4XP_Overlays
      - ./Tiles:/ortho4xp/Tiles
      - ./Ortho4XP.cfg:/ortho4xp/Ortho4XP.cfg
    environment: 
      - DISPLAY=$DISPLAY # Needed for GUI
    entrypoint: ["python3", "Ortho4XP_v130.py"]
